# Generated by Django 5.2.16 on 2026-07-18 19:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DispatchRider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_type',
            field=models.CharField(blank=True, choices=[('kano', 'Kano Delivery'), ('interstate', 'Interstate Delivery'), ('pickup', 'Shop Pickup')], default='kano', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='is_new',
            field=models.BooleanField(default=True, help_text='True until staff opens the order'),
        ),
        migrations.AddField(
            model_name='order',
            name='notifications_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='is_packed',
            field=models.BooleanField(default=False, help_text='Staff checks off during packaging'),
        ),
        migrations.AlterField(
            model_name='order',
            name='checkout_method',
            field=models.CharField(choices=[('online', 'Online Payment (Paystack)'), ('whatsapp', 'WhatsApp Assisted'), ('call', 'Request a Call')], default='online', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('awaiting_payment', 'Awaiting Payment'), ('payment_verified', 'Payment Verified'), ('confirmed', 'Confirmed'), ('pending_packaging', 'Pending Packaging'), ('packaging', 'Packaging In Progress'), ('packed', 'Packed'), ('awaiting_dispatch', 'Awaiting Dispatch'), ('dispatched', 'Dispatched'), ('in_transit', 'In Transit'), ('delivered', 'Delivered'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('returned', 'Returned'), ('delivery_failed', 'Delivery Failed'), ('on_hold', 'On Hold'), ('awaiting_response', 'Awaiting Customer Response')], default='pending', max_length=25),
        ),
        migrations.CreateModel(
            name='DispatchBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(blank=True, max_length=30, unique=True)),
                ('rider_name', models.CharField(blank=True, max_length=150)),
                ('rider_phone', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('prepared', 'Prepared'), ('sent', 'Sent to Park'), ('completed', 'Completed')], default='prepared', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('rider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.dispatchrider')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(blank=True, max_length=25)),
                ('new_status', models.CharField(max_length=25)),
                ('note', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='orders.order')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='PackagePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='packages/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='package_photo', to='orders.order')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DispatchBatchItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch_items', to='orders.dispatchbatch')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispatch_batches', to='orders.order')),
            ],
            options={
                'unique_together': {('batch', 'order')},
            },
        ),
        migrations.CreateModel(
            name='InterstateDispatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=100)),
                ('driver_name', models.CharField(blank=True, max_length=150)),
                ('driver_phone', models.CharField(max_length=20)),
                ('transport_company', models.CharField(blank=True, max_length=200)),
                ('plate_number', models.CharField(blank=True, max_length=20)),
                ('customer_notified', models.BooleanField(default=False)),
                ('notified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interstate_dispatches', to='orders.dispatchbatch')),
            ],
            options={
                'ordering': ['state'],
                'unique_together': {('batch', 'state')},
            },
        ),
    ]
