# Generated by Django 5.2.16 on 2026-07-19 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_dispatchrider_order_delivery_type_order_is_new_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(blank=True, db_index=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('awaiting_payment', 'Awaiting Payment'), ('payment_verified', 'Payment Verified'), ('confirmed', 'Confirmed'), ('pending_packaging', 'Pending Packaging'), ('packaging', 'Packaging In Progress'), ('packed', 'Packed'), ('awaiting_dispatch', 'Awaiting Dispatch'), ('dispatched', 'Dispatched'), ('in_transit', 'In Transit'), ('delivered', 'Delivered'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('returned', 'Returned'), ('delivery_failed', 'Delivery Failed'), ('on_hold', 'On Hold'), ('awaiting_response', 'Awaiting Customer Response')], db_index=True, default='pending', max_length=25),
        ),
    ]
