# Generated by Django 5.2.16 on 2026-07-20 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_phone_login_and_checkout_fields'),
        ('orders', '0003_payment_cancelled_status_and_order_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_mode',
            field=models.CharField(choices=[('home_delivery', 'Home Delivery'), ('pickup', 'Pickup Point')], default='home_delivery', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='pickup_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='core.pickuplocation'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('received', 'Received'), ('payment_confirmed', 'Payment Confirmed'), ('packing', 'Packing'), ('dispatched', 'Dispatched'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded'), ('pending', 'Pending'), ('awaiting_payment', 'Awaiting Payment'), ('payment_verified', 'Payment Verified'), ('confirmed', 'Confirmed'), ('pending_packaging', 'Pending Packaging'), ('packaging', 'Packaging In Progress'), ('packed', 'Packed'), ('awaiting_dispatch', 'Awaiting Dispatch'), ('in_transit', 'In Transit'), ('completed', 'Completed'), ('failed', 'Failed'), ('returned', 'Returned'), ('delivery_failed', 'Delivery Failed'), ('on_hold', 'On Hold'), ('awaiting_response', 'Awaiting Customer Response')], db_index=True, default='received', max_length=25),
        ),
    ]
