# Generated by Django 5.2.16 on 2026-07-16 16:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('role', models.CharField(choices=[('customer', 'Customer'), ('sales', 'Sales Staff'), ('inventory', 'Inventory Staff'), ('dispatch', 'Dispatch Staff'), ('support', 'Customer Support'), ('marketing', 'Marketing Staff'), ('admin', 'Administrator'), ('superadmin', 'Super Administrator')], default='customer', max_length=20)),
                ('preferred_contact', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('sms', 'SMS'), ('call', 'Phone Call')], default='whatsapp', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
