# Generated by Django 5.2.16 on 2026-07-16 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=300)),
                ('banner_type', models.CharField(choices=[('hero', 'Hero Banner'), ('promo', 'Promotional Banner'), ('announcement', 'Announcement')], default='hero', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='banners/')),
                ('link_url', models.URLField(blank=True)),
                ('link_text', models.CharField(blank=True, default='Shop Now', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
