# Generated by Django 5.2.16 on 2026-07-16 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(default='Marina Gadgets Kano', max_length=200)),
                ('tagline', models.CharField(blank=True, default='Premium Gadgets. Trusted Service.', max_length=300)),
                ('about_text', models.TextField(blank=True)),
                ('address', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('whatsapp_number', models.CharField(blank=True, help_text='Include country code, e.g. 2348012345678', max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('currency_symbol', models.CharField(default='₦', max_length=5)),
                ('shipping_fee', models.DecimalField(decimal_places=2, default=1500.0, max_digits=10)),
                ('free_shipping_threshold', models.DecimalField(decimal_places=2, default=50000.0, max_digits=10)),
                ('hero_title', models.CharField(blank=True, default='Premium Gadgets for Every Need', max_length=200)),
                ('hero_subtitle', models.CharField(blank=True, default='Trusted by thousands across Kano. Fast delivery, genuine products, real support.', max_length=300)),
                ('facebook_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('whatsapp_url', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
