# Generated by Django 5.2.16 on 2026-07-18 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='dashboard_poll_interval',
            field=models.PositiveIntegerField(default=30, help_text='How often (seconds) the dashboard checks for new orders'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='default_printer_name',
            field=models.CharField(blank=True, help_text='Name of the receipt/order printer connected to the shop PC', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='notification_sound',
            field=models.FileField(blank=True, help_text='MP3/WAV sound played when a new order arrives on the dashboard', null=True, upload_to='sounds/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='sms_api_key',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='sms_provider',
            field=models.CharField(choices=[('none', 'Disabled'), ('termii', 'Termii (Nigeria)'), ('twilio', 'Twilio SMS')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='support_email',
            field=models.EmailField(blank=True, default='support@marinagadgets.com', max_length=254),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='support_phone',
            field=models.CharField(blank=True, help_text='Customer support line shown in notifications', max_length=30),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='whatsapp_api_key',
            field=models.CharField(blank=True, help_text='API key/token for chosen WhatsApp provider', max_length=500),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='whatsapp_api_secret',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='whatsapp_provider',
            field=models.CharField(choices=[('link', 'WhatsApp Link (Free, manual click)'), ('twilio', 'Twilio WhatsApp API'), ('wati', 'WATI WhatsApp API')], default='link', help_text='How to send WhatsApp messages to customers', max_length=20),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='whatsapp_number',
            field=models.CharField(blank=True, help_text='Include country code e.g. 2348012345678', max_length=30),
        ),
    ]
