# Generated by Django 5.2.16 on 2026-07-20 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_sitesettings_dashboard_poll_interval_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='delivery_estimate_interstate',
            field=models.CharField(default='Outside Kano, delivery is paid directly to the transport company on collection — typically ₦3,000 – ₦8,000 depending on your location and package size', help_text='Display estimate for interstate pickup', max_length=500),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='delivery_estimate_kano',
            field=models.CharField(default='₦1,500 – ₦2,000', help_text='Display estimate for home delivery in Kano', max_length=200),
        ),
        migrations.CreateModel(
            name='DeliverableCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(db_index=True, max_length=100)),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Deliverable City',
                'verbose_name_plural': 'Deliverable Cities',
                'unique_together': {('state', 'name')},
            },
        ),
        migrations.CreateModel(
            name='PickupLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickup_locations', to='core.deliverablecity')),
            ],
            options={
                'verbose_name': 'Pickup Location',
                'verbose_name_plural': 'Pickup Locations',
            },
        ),
    ]
