# Generated by Django 5.2.16 on 2026-07-19 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('success', 'Successful'), ('failed', 'Failed'), ('cancelled', 'Cancelled by User'), ('refunded', 'Refunded')], default='pending', max_length=20),
        ),
    ]
