# Generated by Django 5.2.16 on 2026-07-16 16:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reward_type', models.CharField(choices=[('discount', 'Discount'), ('store_credit', 'Store Credit'), ('free_delivery', 'Free Delivery'), ('exclusive_offer', 'Exclusive Offer'), ('priority_support', 'Priority Support')], max_length=30)),
                ('reason', models.CharField(max_length=300)),
                ('value', models.CharField(blank=True, help_text='e.g., 10% off, ₦500 credit', max_length=100)),
                ('status', models.CharField(choices=[('active', 'Active'), ('redeemed', 'Redeemed'), ('expired', 'Expired')], default='active', max_length=20)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_rewards', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rewards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
