# Generated by Django 5.2.16 on 2026-07-17 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_category_slug_alter_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.CharField(blank=True, default='fa-solid fa-microchip', help_text='FontAwesome class e.g. fa-solid fa-laptop', max_length=100),
        ),
    ]
