# Generated by Django 5.2.16 on 2026-07-18 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_add_icon_to_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['sort_order', 'name'], 'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Leave blank for top-level category. Select parent to make this a subcategory.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategories', to='catalog.category'),
        ),
        migrations.AddField(
            model_name='category',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, help_text='Lower = appears first'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='is_cover',
            field=models.BooleanField(default=False, help_text='Use as cover/primary image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(help_text='Select a subcategory if available', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='catalog.category'),
        ),
        migrations.CreateModel(
            name='ProductVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='products/videos/')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='catalog.product')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
