# Generated by Django 5.2.16 on 2026-07-18 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        ('orders', '0002_dispatchrider_order_delivery_type_order_is_new_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='orders.order'),
        ),
        migrations.AddField(
            model_name='notification',
            name='whatsapp_link',
            field=models.URLField(blank=True, help_text='Pre-filled wa.me link for manual sending'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='event_type',
            field=models.CharField(choices=[('otp', 'OTP'), ('order_received', 'Order Received'), ('payment_confirmed', 'Payment Confirmed'), ('packaging_started', 'Packaging Started'), ('packing', 'Packing Complete'), ('package_photo', 'Package Photo Sent'), ('awaiting_dispatch', 'Awaiting Dispatch'), ('kano_dispatch', 'Kano Dispatch'), ('interstate_handover', 'Interstate Handover'), ('dispatch', 'Dispatch Update'), ('delivered', 'Delivery Completed'), ('delivery_confirm_request', 'Delivery Confirmation Request'), ('delivery_confirmed', 'Delivery Confirmed'), ('delivery_issue', 'Delivery Issue Reported'), ('feedback', 'Feedback Update'), ('reward', 'Reward Issued'), ('general', 'General')], default='general', max_length=30),
        ),
    ]
